GabenShop.WebUI/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GabenShop.Domain.Entities;
using GabenShop.Domain.Abstract;
using GabenShop.WebUI.Models;

namespace GabenShop.WebUI.Controllers
{
    public class CartController : Controller
    {
        private IProductRepository repository;
        private IOrderProcessor orderProcessor;
        public CartController(IProductRepository repository, IOrderProcessor orderProcessor)
        {
            this.repository = repository;            
            this.orderProcessor = orderProcessor;
        }

        public ViewResult Index(Cart cart, string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                Cart = cart,
                ReturnUrl = returnUrl
            });
        }

        public RedirectToRouteResult AddToCart(Cart cart, int productId, string returnUrl)
        {
            Product product = repository.Products
                .FirstOrDefault(g => g.ProductID == productId);

            if (product != null)
            {
                cart.AddItem(product, 1);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        public RedirectToRouteResult RemoveFromCart(Cart cart, int productId, string returnUrl)
        {
            Product product = repository.Products
                .FirstOrDefault(g => g.ProductID == productId);

            if (product != null)
            {
                cart.RemoveLine(product);
            }
            return RedirectToAction("Index", new { returnUrl });
        }
        public PartialViewResult Summary(Cart cart)
        {
            return PartialView(cart);
        }

        //[HttpPost]
        public ViewResult Checkout(Cart cart, ShippingDetails shippingDetails)
        {
            if (cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Извините, ваша корзина пуста!");
            }

            if (ModelState.IsValid)
            {
                orderProcessor.ProcessOrder(cart, shippingDetails);
                cart.Clear();
                return View("Completed");
            }
            else
            {
                return View(shippingDetails);
            }
        }
    }
}

GabenShop.WebUI/Controllers/NavController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GabenShop.Domain.Abstract;


namespace GabenShop.WebUI.Controllers
{
    public class NavController : Controller
    {
        private IProductRepository repository;

        public NavController(IProductRepository repository)
        {
            this.repository = repository;
        }

        public PartialViewResult Menu(string category = null)
        {
            IEnumerable<string> categories = repository.Products
                .Select(game => game.Category)
                .Distinct()
                .OrderBy(x => x);
            return PartialView(categories);
        }
    }
}

GabenShop.WebUI/Controllers/ProductController.cs
using GabenShop.Domain.Abstract;
using GabenShop.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GabenShop.WebUI.Models;

namespace GabenShop.WebUI.Controllers
{
    public class ProductController : Controller
    {
        private IProductRepository repository;
        public int pageSize = 6;
        public ProductController(IProductRepository repository)
        {
            this.repository = repository;
        }

        public ViewResult List(string category, int page = 1, int sort = 1)
        {
            ProductsListViewModel model;
            if(sort == 1)
            {
                model = new ProductsListViewModel
                {
                    Products = repository.Products
                .Where(p => category == null || p.Category == category)
                .OrderByDescending(Product => Product.Price)
                .Skip((page - 1) * pageSize)
                .Take(pageSize),
                    PagingInfo = new PagingInfo
                    {
                        CurrentPage = page,
                        ItemsPerPage = pageSize,
                        TotalItems = category == null ?
                        repository.Products.Count() :
                        repository.Products.Where(Product => Product.Category == category).Count()
                    },
                    CurrentCategory = category,
                    CurrentSort = sort
                };
            }
            else
            {
                model = new ProductsListViewModel
                {
                    Products = repository.Products
                .Where(p => category == null || p.Category == category)
                .OrderBy(Product => Product.Price)
                .Skip((page - 1) * pageSize)
                .Take(pageSize),
                    PagingInfo = new PagingInfo
                    {
                        CurrentPage = page,
                        ItemsPerPage = pageSize,
                        TotalItems = category == null ?
                        repository.Products.Count() :
                        repository.Products.Where(Product => Product.Category == category).Count()
                    },
                    CurrentCategory = category,
                    CurrentSort = sort
                };
            }                   
            return View(model);
        }

        public FileContentResult GetImage(int productID)
        {
            Product product = repository.Products
                .FirstOrDefault(g => g.ProductID == productID);

            if (product != null)
            {
                return File(product.Image, "jpg");
            }
            else
            {
                return null;
            }
        }

        public ActionResult Discount()
        {
            return PartialView("Discount");
        }
    }
}

GabenShop.WebUI/Views/Shared/ProductSummary.cshtml
@model GabenShop.Domain.Entities.Product
<li>
    @if (Model.Image != null)
    {
        <div class="pull-left" style="margin-right: 10px">
            <img class="img-thumbnail" width="128" height="128"
                 src="@Url.Action("GetImage", "Product",
                new { Model.ProductID })" />
        </div>
    }
    else
    {
        <div class="img"><a href="#"><img alt="" src="#"></a></div>
    }

    <div class="info">
        <a class="title" >@Model.Name</a>
        <p>@Model.Description</p>
        <div class="price">
            <span class="st">Цена:</span><strong>@Model.Price.ToString("# ₽")</strong>
        </div>
        <div class="actions">
            @using (Html.BeginForm("AddToCart", "Cart"))//Это для добавления кнопки корзины
            {
                <div>
                    @Html.HiddenFor(x => x.ProductID)
                    @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
                    <input type="submit" style="width: 100%;" value="Добавить в корзину" />
                </div>
            }
        </div>
    </div>
</li>

GabenShop.WebUI/Views/Shared/_AdminLayout.cshtml
@{
    Layout = null;
}
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    @*<link href="~/Content/ErrorStyles.css" rel="stylesheet" />*@
    @*<link rel="stylesheet" href="@Url.Content("~/Content/style.css")" type="text/css" media="screen">
    <link rel="stylesheet" href="@Url.Content("~/Content/style.css")" type="text/css" media="screen">*@
    <script src="~/Scripts/jquery-1.9.1.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <style>
        body{
            background: none;
        }
    </style>
    <title></title>
</head>
<body>
    <div>
        @if (TempData["message"] != null)
        {
            <div class="alert alert-success">@TempData["message"]</div>
        }
        @RenderBody()
    </div>
</body>
</html>

GabenShop.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="@Url.Content("~/Content/style.css")" type="text/css" media="screen">
    <link rel="stylesheet" href="@Url.Content("~/Content/styleRegist.css")" type="text/css" media="screen">
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

    <style>
        #button {
            position: center;
            clear: both;
            text-decoration: none;
            text-align: center;
            padding: 6px 8px;
            margin-left: 10px;
            border: solid 1px #989e9a;
            -webkit-border-radius: 4px;
            -moz-border-radius: 4px;
            border-radius: 4px;
            font: 11px Arial, Helvetica, sans-serif;
            font-weight: bold;            
            color: #ffffff;
            background-color: #05f519;
            background-image: -moz-linear-gradient(top, #05f519 0%, #009e12 100%);
            background-image: -webkit-linear-gradient(top, #05f519 0%, #009e12 100%);
            background-image: -o-linear-gradient(top, #05f519 0%, #009e12 100%);
            background-image: -ms-linear-gradient(top, #05f519 0%,#009e12 100%);
            filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#009e12', endColorstr='#009e12',GradientType=0 );
            background-image: linear-gradient(top, #05f519 0%,#009e12 100%);
            -webkit-box-shadow: 0px 0px 2px #bababa, inset 0px 0px 1px #ffffff;
            -moz-box-shadow: 0px 0px 2px #bababa, inset 0px 0px 1px #ffffff;
            box-shadow: 0px 0px 2px #bababa, inset 0px 0px 1px #ffffff;
        }

            #button:hover {
                background-color: #ffd800;
            }
    </style>
    <script>
    </script>
</head>
<body>
    <div class="container">
        <header>
            <nav>
                <ul>
                    <li class="selected"><a href="/">Главная</a></li>                  
                    @Html.Action("UserBlock", "Account")                    
                </ul>
            </nav>
            <section id="submenu">                
                <ul>
                    @Html.Action("Menu", "Nav")
                </ul>
            </section>
        </header>

        <div id="main">
            @RenderBody()
        </div>

        <footer>
            <div style="color:black; margin-left:23%">
                <h2>Created by b1-IFST-21 spring-summer 2017 before session</h2>
                <h4>We dont know what write here, sorry</h4>
            </div>
        </footer>
    </div>
</body>
</html>